apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: inventario-system
  labels:
    app: grafana
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: grafana
  type: ClusterIP
