apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: inventario-system
  labels:
    app: inventario
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventario
      tier: backend
  template:
    metadata:
      labels:
        app: inventario
        tier: backend
    spec:
      containers:
      - name: php-fpm
        image: ${ECR_REPOSITORY_URL}/inventario-backend:latest
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 9000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
