apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: inventario-system
  labels:
    app: inventario
    tier: database
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: inventario
    tier: database
  clusterIP: None
