apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: inventario-system
data:
  my.cnf: |
    [mysqld]
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    default-authentication-plugin=mysql_native_password
    
    [client]
    default-character-set=utf8mb4
