apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: inventario-system
  labels:
    app: inventario
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: inventario
    tier: frontend
