apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.namespace.name }}
data:
  DB_HOST: {{ .Values.backend.config.DB_HOST | quote }}
  DB_NAME: {{ .Values.backend.config.DB_NAME | quote }}
  DB_USER: {{ .Values.backend.config.DB_USER | quote }}
