apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: {{ .Values.namespace.name }}
data:
  my.cnf: |
    [mysqld]
    character-set-server={{ .Values.database.config.characterSetServer }}
    collation-server={{ .Values.database.config.collationServer }}
    default-authentication-plugin={{ .Values.database.config.authenticationPlugin }}
    
    [client]
    default-character-set={{ .Values.database.config.characterSetClient }}
