apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: {{ .Values.namespace.name }}
  labels:
    app: inventario
    tier: database
spec:
  ports:
  - port: {{ .Values.database.service.port }}
    targetPort: {{ .Values.database.service.targetPort }}
    name: mysql
  - port: 9104
    targetPort: 9104
    name: metrics
  selector:
    app: inventario
    tier: database
  clusterIP: None
