apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.database.secrets.rootPassword }}
  MYSQL_DATABASE: {{ .Values.database.secrets.database }}
  MYSQL_USER: {{ .Values.database.secrets.user }}
  MYSQL_PASSWORD: {{ .Values.database.secrets.password }}
