apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: {{ .Values.namespace.name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"
    {{- if .Values.ingress.annotations }}
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  rules:
  - http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.frontend.name }}-service
            port:
              number: {{ .Values.frontend.service.port }}
      - path: /api/(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.name }}-service
            port:
              number: {{ .Values.backend.service.port }}
      - path: /prometheus/?(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.monitoring.prometheus.name }}-service
            port:
              number: {{ .Values.monitoring.prometheus.service.port }}
      - path: /grafana/?(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.monitoring.grafana.name }}-service
            port:
              number: {{ .Values.monitoring.grafana.service.port }}
