apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Values.namespace.name }}
  labels:
    app: prometheus
spec:
  type: {{ .Values.monitoring.prometheus.service.type }}
  ports:
  - port: {{ .Values.monitoring.prometheus.service.port }}
    targetPort: {{ .Values.monitoring.prometheus.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app: prometheus
